// <auto-generated/>

using System.Reflection;
using RecSys.Platform.Data.FluentMigrator;
using RecSys.Platform.Extensions;

var builder = WebApplication
    .CreateBuilder(args)
    .UsePlatform();
var services = builder.Services;
var configuration = builder.Configuration;

#region DI

services.AddControllers();
services.AddEndpointsApiExplorer();
services.AddSwagger("rec-sys-api");
services.AddSerilogLogger();

#endregion

var app = builder.Build();

#region App

app.UseSwagger();
app.UseSwaggerUI();
app.MapControllers();

#endregion

await app.RunOrMigrateAsync(args);
